---
# This playbook prints a simple debug message
- name: Hello World example
  hosts: 127.0.0.1
  connection: local

  vars:
    hello: "Hello World!!!"

  tasks:
  - name: Print debug message
    debug:
      msg: "{{ hello }}"
