---
# This playbook prints a simple debug message
- name: ref-resolver-example
  hosts: localhost

  tasks:
  - name: Print name
    debug:
      msg: "Alex"
  
  - name: Print location
    debug:
      msg: "London"
