---
# This playbook prints a simple debug message
- name: ref-resolver-example
  hosts: localhost

  tasks:
  - name: Print location
    debug:
      msg: "{{ location }}"

  - name: Copy location value
    set_fact:
      cacheable: True
      visible_location: "{{ location }}"

  - name: Print visible location
    debug:
      msg: "{{ visible_location }}"

  - name: Print name
    debug:
      msg: "{{ name }}"
  